# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robo_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='robo_message.proto',
  package='robo_messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12robo_message.proto\x12\rrobo_messages\"\xee\x04\n\x0bRoboMessage\x12\x31\n\x06header\x18\x01 \x01(\x0b\x32!.robo_messages.RoboMessage.Header\x12\x38\n\nagent_info\x18\x02 \x01(\x0b\x32$.robo_messages.RoboMessage.AgentInfo\x12<\n\x0c\x61gent_action\x18\x03 \x01(\x0b\x32&.robo_messages.RoboMessage.AgentAction\x1a)\n\x06Header\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x1a\xaa\x02\n\tAgentInfo\x12\"\n\x1astacked_vector_observation\x18\x01 \x03(\x02\x12\x1b\n\x13visual_observations\x18\x02 \x03(\x0c\x12\x18\n\x10text_observation\x18\x03 \x01(\t\x12\x1d\n\x15stored_vector_actions\x18\x04 \x03(\x02\x12\x1b\n\x13stored_text_actions\x18\x05 \x01(\t\x12\x10\n\x08memories\x18\x06 \x03(\x02\x12\x0e\n\x06reward\x18\x07 \x01(\x02\x12\x0c\n\x04\x64one\x18\x08 \x01(\x08\x12\x18\n\x10max_step_reached\x18\t \x01(\x08\x12\n\n\x02id\x18\n \x01(\x05\x12\x13\n\x0b\x61\x63tion_mask\x18\x0b \x03(\x08\x12\x1b\n\x13vector_actions_size\x18\x0c \x01(\x05\x1a\\\n\x0b\x41gentAction\x12\x16\n\x0evector_actions\x18\x01 \x03(\x02\x12\x14\n\x0ctext_actions\x18\x02 \x01(\t\x12\x10\n\x08memories\x18\x03 \x03(\x02\x12\r\n\x05value\x18\x04 \x01(\x02\x62\x06proto3')
)




_ROBOMESSAGE_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='robo_messages.RoboMessage.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='robo_messages.RoboMessage.Header.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='robo_messages.RoboMessage.Header.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=265,
)

_ROBOMESSAGE_AGENTINFO = _descriptor.Descriptor(
  name='AgentInfo',
  full_name='robo_messages.RoboMessage.AgentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stacked_vector_observation', full_name='robo_messages.RoboMessage.AgentInfo.stacked_vector_observation', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visual_observations', full_name='robo_messages.RoboMessage.AgentInfo.visual_observations', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text_observation', full_name='robo_messages.RoboMessage.AgentInfo.text_observation', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stored_vector_actions', full_name='robo_messages.RoboMessage.AgentInfo.stored_vector_actions', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stored_text_actions', full_name='robo_messages.RoboMessage.AgentInfo.stored_text_actions', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memories', full_name='robo_messages.RoboMessage.AgentInfo.memories', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reward', full_name='robo_messages.RoboMessage.AgentInfo.reward', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='done', full_name='robo_messages.RoboMessage.AgentInfo.done', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_step_reached', full_name='robo_messages.RoboMessage.AgentInfo.max_step_reached', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='robo_messages.RoboMessage.AgentInfo.id', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_mask', full_name='robo_messages.RoboMessage.AgentInfo.action_mask', index=10,
      number=11, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vector_actions_size', full_name='robo_messages.RoboMessage.AgentInfo.vector_actions_size', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None, 
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=566,
)

_ROBOMESSAGE_AGENTACTION = _descriptor.Descriptor(
  name='AgentAction',
  full_name='robo_messages.RoboMessage.AgentAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector_actions', full_name='robo_messages.RoboMessage.AgentAction.vector_actions', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text_actions', full_name='robo_messages.RoboMessage.AgentAction.text_actions', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memories', full_name='robo_messages.RoboMessage.AgentAction.memories', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='robo_messages.RoboMessage.AgentAction.value', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=568,
  serialized_end=660,
)

_ROBOMESSAGE = _descriptor.Descriptor(
  name='RoboMessage',
  full_name='robo_messages.RoboMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='robo_messages.RoboMessage.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agent_info', full_name='robo_messages.RoboMessage.agent_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agent_action', full_name='robo_messages.RoboMessage.agent_action', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ROBOMESSAGE_HEADER, _ROBOMESSAGE_AGENTINFO, _ROBOMESSAGE_AGENTACTION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=660,
)

_ROBOMESSAGE_HEADER.containing_type = _ROBOMESSAGE
_ROBOMESSAGE_AGENTINFO.containing_type = _ROBOMESSAGE
_ROBOMESSAGE_AGENTACTION.containing_type = _ROBOMESSAGE
_ROBOMESSAGE.fields_by_name['header'].message_type = _ROBOMESSAGE_HEADER
_ROBOMESSAGE.fields_by_name['agent_info'].message_type = _ROBOMESSAGE_AGENTINFO
_ROBOMESSAGE.fields_by_name['agent_action'].message_type = _ROBOMESSAGE_AGENTACTION
DESCRIPTOR.message_types_by_name['RoboMessage'] = _ROBOMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RoboMessage = _reflection.GeneratedProtocolMessageType('RoboMessage', (_message.Message,), dict(

  Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
    DESCRIPTOR = _ROBOMESSAGE_HEADER,
    __module__ = 'robo_message_pb2'
    # @@protoc_insertion_point(class_scope:robo_messages.RoboMessage.Header)
    ))
  ,

  AgentInfo = _reflection.GeneratedProtocolMessageType('AgentInfo', (_message.Message,), dict(
    DESCRIPTOR = _ROBOMESSAGE_AGENTINFO,
    __module__ = 'robo_message_pb2'
    # @@protoc_insertion_point(class_scope:robo_messages.RoboMessage.AgentInfo)
    ))
  ,

  AgentAction = _reflection.GeneratedProtocolMessageType('AgentAction', (_message.Message,), dict(
    DESCRIPTOR = _ROBOMESSAGE_AGENTACTION,
    __module__ = 'robo_message_pb2'
    # @@protoc_insertion_point(class_scope:robo_messages.RoboMessage.AgentAction)
    ))
  ,
  DESCRIPTOR = _ROBOMESSAGE,
  __module__ = 'robo_message_pb2'
  # @@protoc_insertion_point(class_scope:robo_messages.RoboMessage)
  ))
_sym_db.RegisterMessage(RoboMessage)
_sym_db.RegisterMessage(RoboMessage.Header)
_sym_db.RegisterMessage(RoboMessage.AgentInfo)
_sym_db.RegisterMessage(RoboMessage.AgentAction)


# @@protoc_insertion_point(module_scope)
